travis:
  secure:
    BINSTAR_TOKEN: HnuHodCz5NftBwzWuAbpiaqFXM9xXihICvFrEXifvD7qdLdZxvh/DJaauAKfQSb88LrHa9e9KTTxSsaVAoapPEjK5Xn+8XYoAtCPn7Cnu+nFcQHV2LCK1yQ098/LvQt346QkE3X9dXzWgCrXoAbqk7tM+uwOQJ0bP5X89dd27/A8F4jS0iYzcYSsGKqjBjumRb+WaOaA36TONx5CTAioq/u6JfmdRRAqrGD3eL2ONeQWYkEVsDj+xoam1HLXgQGX2tYXJLk+kmyVz5f0wFlPQLbHTcMO/yXMZfZhW9dMCFGATly4cUVy0iJEGg5GDVgeSnROyUH1UGMsQ2H6qgCXBAI8r8e8LWJSJagGTTgpmPNCNZ/MIwKpP/CdiW8lLqIX9tlOMqOurjgB0d78NjS10eADk64eqbGDhWQLieZ+P/0wSW9/AUWZB8wdCHsn7KJEqHhAB0iynfcUFtIHKaavADdFlvxPBBbddXDjOxqfvgfBs373XsvyzmeqdsxS69rZHOrPAFpJwWHlQNI0sVt4vg1NJo8Z5dsBkmVKDXwGOEOTzdKLpKTMcU9nkUX9iQ9hfzVP9glAKcAG7hP4EM1XIKTj61wMVY2y+gJdk2v1uD5aRu1jomk1PhFfVxf5NwXnqDKz0MUNS/HrNntM4TYEnveMI7JbWIalTK9aPzfLp3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
